// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXIqPpshziQRqVwnwN2Ini4bwL5HkiVl0',
    appId: '1:851476540070:web:5476b5f1bf59ff9fb26267',
    messagingSenderId: '851476540070',
    projectId: 'beacon-app-g8',
    authDomain: 'beacon-app-g8.firebaseapp.com',
    storageBucket: 'beacon-app-g8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqxZe4VA6BTi2CsediT2nZtBlyR9yf5mc',
    appId: '1:851476540070:android:476edd75e2324c8cb26267',
    messagingSenderId: '851476540070',
    projectId: 'beacon-app-g8',
    storageBucket: 'beacon-app-g8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxbXMn8jgF-z5hzQVKi6egSJV8aGQzMtA',
    appId: '1:851476540070:ios:7ce5c540c7d6fd6cb26267',
    messagingSenderId: '851476540070',
    projectId: 'beacon-app-g8',
    storageBucket: 'beacon-app-g8.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxbXMn8jgF-z5hzQVKi6egSJV8aGQzMtA',
    appId: '1:851476540070:ios:7ce5c540c7d6fd6cb26267',
    messagingSenderId: '851476540070',
    projectId: 'beacon-app-g8',
    storageBucket: 'beacon-app-g8.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXIqPpshziQRqVwnwN2Ini4bwL5HkiVl0',
    appId: '1:851476540070:web:420dba8d55bafbefb26267',
    messagingSenderId: '851476540070',
    projectId: 'beacon-app-g8',
    authDomain: 'beacon-app-g8.firebaseapp.com',
    storageBucket: 'beacon-app-g8.firebasestorage.app',
  );
}
