import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'package:assignment/screens/login_screen.dart';
import 'package:assignment/screens/home_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await Firebase.initializeApp(
    options: const FirebaseOptions(
      apiKey: "AIzaSyDXIqPpshziQRqVwnwN2Ini4bwL5HkiVl0",
      authDomain: "beacon-app-g8.firebaseapp.com",
      projectId: "beacon-app-g8",
      storageBucket: "beacon-app-g8.firebasestorage.app",
      messagingSenderId: "851476540070",
      appId: "1:851476540070:web:5476b5f1bf59ff9fb26267",
    ),
  );

  runApp(const APUConnectApp());
}

class APUConnectApp extends StatelessWidget {
  const APUConnectApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'APU Connect',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      home: const AuthWrapper(),
    );
  }
}

// Checks auth state to show either Login or Home
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Center(child: CircularProgressIndicator());
        }
        if (snapshot.hasData) {
          return const MainNavigationScreen();// User is logged in
        }
        return const LoginScreen(); // User is not logged in
      },
    );
  }
}